"""Local Ollama-based radiology report generation from structured metadata only.

This module is independent of template-based reporting in :mod:`analysis.report`.
It never receives raw imaging data—only JSON-serialisable metadata produced by
the inference pipeline.
"""
from __future__ import annotations

import asyncio
import json
import logging
import re
from typing import Any

import ollama

from backend.config import (
    OLLAMA_HOST,
    OLLAMA_MODEL,
    OLLAMA_TEMPERATURE,
    OLLAMA_TIMEOUT_SECONDS,
)

logger = logging.getLogger(__name__)

_SECTION_KEYS = ("findings", "impression", "recommendations")
_SECTION_HEADERS = ("FINDINGS", "IMPRESSION", "RECOMMENDATIONS")

# Output length guards (keeps gemma:2b reports short and scannable)
_MAX_WORDS_PER_SECTION = {"findings": 70, "impression": 35, "recommendations": 35}
_MAX_CHARS_PER_SECTION = {"findings": 520, "impression": 280, "recommendations": 280}
_OLLAMA_NUM_PREDICT = 220

_SECTION_HEADER_LINE = re.compile(
    r"(?im)^\s*(?:#{1,3}\s*)?(?:\*\*)?\s*"
    r"(FINDINGS|IMPRESSION|RECOMMENDATIONS)\s*(?:\*\*)?\s*:\s*(.*)$",
)
_SECTION_SPLIT = re.compile(
    r"(?i)\b(FINDINGS|IMPRESSION|RECOMMENDATIONS)\s*:\s*",
)

_MARKDOWN_CHARS = re.compile(r"[*_`#>|]")
_BULLET_PREFIX = re.compile(r"^\s*(?:[-*•]|\d+[.)])\s+", re.MULTILINE)
_MULTI_SPACE = re.compile(r" {2,}")
_MULTI_NEWLINE = re.compile(r"\n{3,}")

_ACRONYMS = {
    "mri": "MRI",
    "dwi": "DWI",
    "ai": "AI",
    "ml": "mL",
}

DISCLAIMER = (
    "This report was generated by a local LLM (Ollama) using AI-derived lesion "
    "metrics only. It is NOT a clinical diagnostic device. All findings must be "
    "confirmed by a qualified radiologist before any clinical use."
)


class LLMReportError(Exception):
    """Base error for LLM report generation failures."""


class LLMConnectionError(LLMReportError):
    """Ollama server unreachable or returned a connection-level failure."""


class LLMTimeoutError(LLMReportError):
    """Report generation exceeded the configured timeout."""


class LLMResponseError(LLMReportError):
    """Ollama responded but the payload could not be parsed into report sections."""


def build_metadata_from_prediction_cache(entry: dict[str, Any]) -> dict[str, Any]:
    """Build a JSON-safe metadata dict from a :data:`prediction_cache` entry."""
    from backend.services.inference import serialise_findings

    case = entry["case"]
    volume = entry["volume"]
    H, W, D = volume.shape
    return {
        "patient_id": entry.get("case_label", "anonymised"),
        "modality": "Diffusion-Weighted Imaging (DWI), MRI",
        "ai_system": "2D U-Net stroke lesion segmentation",
        "shape": [int(H), int(W), int(D)],
        "spacing_mm": [round(float(s), 2) for s in entry["spacing"]],
        "voxel_volume_ml": round(float(entry["voxel_volume_ml"]), 4),
        "n_lesions": int(case.n_lesions),
        "total_volume_ml": round(float(case.total_volume_ml), 3),
        "largest_volume_ml": round(float(case.largest_volume_ml), 3),
        "side_distribution": dict(case.side_distribution),
        "per_lesion_findings": serialise_findings(case),
    }


def _assess_metadata(metadata: dict[str, Any]) -> tuple[bool, list[str]]:
    """Return whether metadata supports a quantitative report and any limitations."""
    limitations: list[str] = []

    has_lesion_count = "n_lesions" in metadata and metadata["n_lesions"] is not None
    has_volumes = any(
        metadata.get(k) is not None
        for k in ("total_volume_ml", "largest_volume_ml")
    )
    findings = metadata.get("per_lesion_findings") or metadata.get("findings")
    has_per_lesion = isinstance(findings, list) and len(findings) > 0

    if not (has_lesion_count or has_volumes or has_per_lesion):
        limitations.append(
            "Insufficient quantitative lesion metrics (lesion count, volumes, or "
            "per-lesion details missing)."
        )

    if not metadata.get("modality"):
        limitations.append("Imaging modality not specified in metadata.")

    if metadata.get("n_lesions", 0) > 0 and not has_per_lesion and not has_volumes:
        limitations.append(
            "Lesion count present but per-lesion detail and aggregate volumes are absent."
        )

    sufficient = not any(
        "Insufficient quantitative" in lim for lim in limitations
    )
    return sufficient, limitations


def _format_side_distribution(dist: dict[str, Any]) -> str:
    if not dist:
        return ""
    parts = [f"{v} on the {k}" for k, v in dist.items()]
    return ", ".join(parts)


def _deterministic_sections(
    metadata: dict[str, Any],
    limitations: list[str] | None = None,
) -> dict[str, str]:
    """Build a safe, metadata-only report without calling the LLM."""
    limitations = limitations or []
    n = int(metadata.get("n_lesions", 0) or 0)
    total_ml = metadata.get("total_volume_ml")
    largest_ml = metadata.get("largest_volume_ml")
    sides = _format_side_distribution(metadata.get("side_distribution") or {})
    modality = metadata.get("modality", "DWI MRI")
    findings_list = metadata.get("per_lesion_findings") or metadata.get("findings") or []

    lim_note = (
        " Reporting is limited by incomplete AI-derived metadata; "
        "do not infer additional findings."
        if limitations
        else ""
    )

    if limitations and not any(
        metadata.get(k) is not None
        for k in ("n_lesions", "total_volume_ml", "largest_volume_ml")
    ):
        return {
            "findings": (
                f"AI-assisted analysis of {modality} could not be fully summarised "
                f"because quantitative lesion metrics were not provided.{lim_note}"
            ),
            "impression": (
                "Interpretation is indeterminate from the available metadata. "
                "Formal radiologist review is required."
            ),
            "recommendations": (
                "Clinical correlation and qualified radiologist interpretation "
                "are recommended before any clinical action."
            ),
        }

    if n == 0:
        findings = (
            f"No definite acute ischaemic lesion identified on AI-assisted "
            f"segmentation of {modality}.{lim_note}"
        )
        impression = (
            "Negative for acute infarct on AI-assisted DWI screening within the "
            "analysed volume."
        )
        recommendations = (
            "Clinical correlation and radiologist review are recommended if "
            "clinical suspicion persists."
        )
    else:
        vol_parts: list[str] = []
        if total_ml is not None:
            vol_parts.append(f"total estimated lesion volume {float(total_ml):.2f} mL")
        if largest_ml is not None:
            vol_parts.append(f"largest focus {float(largest_ml):.2f} mL")
        vol_txt = "; ".join(vol_parts) if vol_parts else "volumes per metadata"

        findings = (
            f"AI segmentation demonstrates {n} acute ischaemic focus"
            f"{'es' if n != 1 else ''} on {modality}"
            + (f" ({sides})." if sides else ".")
            + f" {vol_txt.capitalize()}."
        )
        if findings_list:
            detail = findings_list[0]
            region = detail.get("region") or detail.get("region_axial")
            side = detail.get("side")
            vol = detail.get("volume_ml")
            extras = []
            if vol is not None:
                extras.append(f"largest listed focus {float(vol):.2f} mL")
            if side:
                extras.append(f"{side} hemisphere")
            if region:
                extras.append(str(region))
            if extras:
                findings += " Dominant focus: " + ", ".join(extras) + "."

        impression = (
            f"Findings compatible with acute ischaemic stroke on AI-assisted analysis "
            f"({n} focus{'es' if n != 1 else ''})."
        )
        recommendations = (
            "Urgent stroke pathway and clinical correlation are advised when "
            "symptoms are present. Treatment decisions require radiologist confirmation."
        )
        if total_ml is not None and float(total_ml) >= 70:
            recommendations = (
                "Large estimated lesion burden on AI metrics; urgent neurology "
                "review and formal imaging review are advised. Treatment decisions "
                "require radiologist confirmation."
            )
        elif total_ml is not None and float(total_ml) < 10:
            recommendations = (
                "Small AI-estimated lesion burden; clinical correlation and "
                "radiologist review are recommended."
            )

    return {
        "findings": findings + (f" Limitations: {' '.join(limitations)}" if limitations else ""),
        "impression": impression,
        "recommendations": recommendations,
    }


def _build_messages(
    metadata: dict[str, Any],
    limitations: list[str],
) -> list[dict[str, str]]:
    """Construct prompts with strict radiology formatting rules."""
    compact_meta = {k: v for k, v in metadata.items() if v is not None}
    metadata_json = json.dumps(compact_meta, separators=(",", ":"), default=str)
    limitation_txt = (
        "METADATA LIMITATIONS (acknowledge briefly in FINDINGS, do not expand beyond): "
        + "; ".join(limitations)
        if limitations
        else ""
    )

    system = (
        "You write brief hospital radiology reports from AI stroke-segmentation metadata only.\n\n"
        "FORMAT (mandatory — copy exactly):\n"
        "FINDINGS:\n"
        "<plain prose>\n"
        "IMPRESSION:\n"
        "<plain prose>\n"
        "RECOMMENDATIONS:\n"
        "<plain prose>\n\n"
        "STYLE:\n"
        "- Terse, declarative, professional radiology tone.\n"
        "- FINDINGS: 2-3 sentences max. IMPRESSION: 1 sentence. RECOMMENDATIONS: 1 sentence.\n"
        "- Total length under 120 words.\n"
        "- Complete sentences. No preamble or closing remarks.\n\n"
        "STRICT PROHIBITIONS:\n"
        "- Use ONLY facts in METADATA JSON. No invented history, symptoms, labs, or diagnoses.\n"
        "- No speculative language (e.g. 'possible', 'may represent', 'cannot exclude').\n"
        "- No markdown, headings, bullets, numbered lists, asterisks, or line-start dashes.\n"
        "- No repetition across sections.\n"
        "- Do not restate the same volume or count in multiple sections.\n"
        "- Do not name treatments (e.g. thrombectomy, tPA) unless total_volume_ml >= 70 in metadata.\n"
        "- RECOMMENDATIONS must stay conservative: correlation, radiologist review, "
        "urgent review only when volumes in metadata justify it.\n"
        "- If n_lesions is 0, state no definite acute ischaemic lesion on AI segmentation.\n"
        "- If metadata is incomplete, state the limitation in FINDINGS in one short clause; "
        "do not fabricate missing values."
    )
    user = (
        "Write the three sections using ONLY this METADATA JSON.\n"
        f"{limitation_txt}\n\n"
        f"METADATA JSON:{metadata_json}"
    )
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": user},
    ]


def _parse_sections(raw_text: str) -> dict[str, str]:
    """Parse FINDINGS / IMPRESSION / RECOMMENDATIONS with multiple strategies."""
    text = (raw_text or "").strip()
    if not text:
        raise LLMResponseError("Model returned empty content.")

    parsed = _parse_by_header_lines(text)
    if parsed:
        return parsed

    parsed = _parse_by_split(text)
    if parsed:
        return parsed

    raise LLMResponseError(
        "Could not parse structured sections (expected FINDINGS:, IMPRESSION:, "
        "RECOMMENDATIONS:)."
    )


def _parse_by_header_lines(text: str) -> dict[str, str] | None:
    """Match section headers at line start (optional markdown wrappers)."""
    matches = list(_SECTION_HEADER_LINE.finditer(text))
    if not matches:
        return None

    sections: dict[str, str] = {}
    for i, match in enumerate(matches):
        name = match.group(1).upper()
        inline = (match.group(2) or "").strip()
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = inline + ("\n" + text[start:end] if start < end else "")
        body = body.strip()
        if body:
            sections[name] = _merge_section_text(sections.get(name), body)

    return _validate_parsed_sections(sections)


def _parse_by_split(text: str) -> dict[str, str] | None:
    """Split on inline section headers (e.g. 'IMPRESSION: ... FINDINGS:')."""
    parts = _SECTION_SPLIT.split(text)
    if len(parts) < 3:
        return None

    sections: dict[str, str] = {}
    # parts[0] is often preamble; then alternating name / body
    i = 1
    while i + 1 < len(parts):
        name = parts[i].strip().upper()
        body = parts[i + 1].strip()
        if name in _SECTION_HEADERS and body:
            sections[name] = _merge_section_text(sections.get(name), body)
        i += 2

    return _validate_parsed_sections(sections)


def _merge_section_text(existing: str | None, new: str) -> str:
    if not existing:
        return new.strip()
    if existing.strip().lower() == new.strip().lower():
        return existing.strip()
    return f"{existing.strip()} {new.strip()}".strip()


def _validate_parsed_sections(sections: dict[str, str]) -> dict[str, str] | None:
    missing = [h for h in _SECTION_HEADERS if h not in sections or not sections[h].strip()]
    if missing:
        return None
    return {
        "findings": sections["FINDINGS"],
        "impression": sections["IMPRESSION"],
        "recommendations": sections["RECOMMENDATIONS"],
    }


def _strip_markdown(text: str) -> str:
    text = _MARKDOWN_CHARS.sub("", text)
    text = _BULLET_PREFIX.sub("", text)
    return text


def _dedupe_lines(text: str) -> str:
    """Remove duplicate lines and near-duplicate sentences."""
    lines: list[str] = []
    seen_norm: set[str] = set()
    for raw_line in text.splitlines():
        line = " ".join(raw_line.split()).strip()
        if not line:
            continue
        norm = line.lower()
        if norm in seen_norm:
            continue
        seen_norm.add(norm)
        lines.append(line)

    if not lines:
        return ""

    # Also dedupe sentences within a single-line paragraph
    joined = " ".join(lines)
    sentences = re.split(r"(?<=[.!?])\s+", joined)
    out: list[str] = []
    seen_sent: set[str] = set()
    for sent in sentences:
        sent = sent.strip()
        if not sent:
            continue
        norm = sent.lower()
        if norm in seen_sent:
            continue
        seen_sent.add(norm)
        out.append(sent)
    return " ".join(out)


def _normalize_acronyms(text: str) -> str:
    for lower, proper in _ACRONYMS.items():
        text = re.sub(rf"\b{re.escape(lower)}\b", proper, text, flags=re.IGNORECASE)
    return text


def _normalize_spacing(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = _MULTI_NEWLINE.sub("\n\n", text)
    text = _MULTI_SPACE.sub(" ", text)
    return text.strip()


def _capitalize_lead(text: str) -> str:
    text = text.strip()
    if not text:
        return text
    return text[0].upper() + text[1:]


def _truncate_section(text: str, key: str) -> str:
    max_words = _MAX_WORDS_PER_SECTION[key]
    max_chars = _MAX_CHARS_PER_SECTION[key]

    words = text.split()
    if len(words) > max_words:
        text = " ".join(words[:max_words])
        if not text.endswith("."):
            text += "."

    if len(text) > max_chars:
        cut = text[: max_chars - 1].rsplit(" ", 1)[0]
        text = cut.rstrip(" ,;:") + "."

    return text


def _postprocess_section(text: str, key: str) -> str:
    text = _strip_markdown(text)
    text = _normalize_spacing(text)
    text = _dedupe_lines(text)
    text = _normalize_acronyms(text)
    text = _capitalize_lead(text)
    text = _truncate_section(text, key)
    return text


def _postprocess_sections(sections: dict[str, str]) -> dict[str, str]:
    return {key: _postprocess_section(sections[key], key) for key in _SECTION_KEYS}


def _format_as_raw(sections: dict[str, str]) -> str:
    return (
        f"FINDINGS:\n{sections['findings']}\n\n"
        f"IMPRESSION:\n{sections['impression']}\n\n"
        f"RECOMMENDATIONS:\n{sections['recommendations']}"
    )


def _get_async_client() -> ollama.AsyncClient:
    return ollama.AsyncClient(host=OLLAMA_HOST, timeout=OLLAMA_TIMEOUT_SECONDS)


async def _call_ollama(
    metadata: dict[str, Any],
    limitations: list[str],
) -> str:
    """Invoke Ollama chat API; raises domain errors on failure."""
    client = _get_async_client()
    messages = _build_messages(metadata, limitations)
    try:
        response = await client.chat(
            model=OLLAMA_MODEL,
            messages=messages,
            options={
                "temperature": OLLAMA_TEMPERATURE,
                "num_predict": _OLLAMA_NUM_PREDICT,
            },
        )
    except asyncio.TimeoutError as exc:
        raise LLMTimeoutError(
            f"Ollama request timed out after {OLLAMA_TIMEOUT_SECONDS}s."
        ) from exc
    except ConnectionError as exc:
        raise LLMConnectionError(
            f"Cannot connect to Ollama at {OLLAMA_HOST}. Is the server running?"
        ) from exc
    except Exception as exc:
        err_msg = str(exc).lower()
        if "timeout" in err_msg or "timed out" in err_msg:
            raise LLMTimeoutError(str(exc)) from exc
        if "connect" in err_msg or "connection" in err_msg:
            raise LLMConnectionError(str(exc)) from exc
        logger.exception("Ollama chat failed")
        raise LLMReportError(f"Ollama request failed: {exc}") from exc

    content = getattr(getattr(response, "message", None), "content", None)
    if content is None and isinstance(response, dict):
        content = response.get("message", {}).get("content")
    if not content or not str(content).strip():
        raise LLMResponseError("Ollama returned an empty message.")
    return str(content).strip()


async def generate_llm_report(metadata: dict[str, Any]) -> dict[str, Any]:
    """Generate Findings, Impression, and Recommendations from metadata via Ollama.

    Parameters
    ----------
    metadata:
        JSON-serialisable dict of lesion metrics (volumes, counts, per-lesion
        details, spacing, etc.). Must not contain raw image arrays.

    Returns
    -------
    dict
        Keys: ``findings``, ``impression``, ``recommendations``, ``model``,
        ``disclaimer``, and ``raw`` (normalised three-section text for audit).

    Raises
    ------
    LLMConnectionError, LLMTimeoutError, LLMResponseError, LLMReportError
    """
    if not metadata:
        raise LLMReportError("metadata must be a non-empty dict.")

    sufficient, limitations = _assess_metadata(metadata)
    if not sufficient:
        logger.info("Insufficient metadata for LLM report; using deterministic fallback.")
        sections = _deterministic_sections(metadata, limitations)
        sections = _postprocess_sections(sections)
        return {
            **sections,
            "model": OLLAMA_MODEL,
            "disclaimer": DISCLAIMER,
            "raw": _format_as_raw(sections),
            "fallback": True,
        }

    async with asyncio.timeout(OLLAMA_TIMEOUT_SECONDS):
        raw = await _call_ollama(metadata, limitations)

    try:
        sections = _parse_sections(raw)
    except LLMResponseError:
        logger.warning("LLM parse failed; using deterministic metadata-only fallback.")
        sections = _deterministic_sections(metadata, limitations)

    sections = _postprocess_sections(sections)

    # If post-processing emptied a section, refill from safe fallback
    for key in _SECTION_KEYS:
        if not sections.get(key, "").strip():
            refill = _deterministic_sections(metadata, limitations)
            sections[key] = _postprocess_section(refill[key], key)

    return {
        **sections,
        "model": OLLAMA_MODEL,
        "disclaimer": DISCLAIMER,
        "raw": _format_as_raw(sections),
        "fallback": False,
    }
