"""Hospital-style PDF export for template and AI radiology reports (ReportLab)."""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from io import BytesIO
from typing import Any, Literal

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from analysis.report import generate_report
from backend.config import API_TITLE, API_VERSION
from backend.services.llm_report_service import (
    DISCLAIMER as LLM_DISCLAIMER,
    build_metadata_from_prediction_cache,
    generate_llm_report,
)

ReportType = Literal["template", "ai"]

# Brand palette (aligned with frontend clinical / brand tokens)
_COLOR_HEADER = colors.HexColor("#0F766E")
_COLOR_HEADER_ACCENT = colors.HexColor("#14B8A6")
_COLOR_INK = colors.HexColor("#0F172A")
_COLOR_MUTED = colors.HexColor("#64748B")
_COLOR_BORDER = colors.HexColor("#E2E8F0")
_COLOR_SECTION_BG = colors.HexColor("#F8FAFC")
_COLOR_WHITE = colors.white

_REPORT_TITLE = "AI-Powered Stroke Lesion Analysis Report"
_FOOTER_LINE = "Generated by AI-Powered Stroke Lesion Analysis System"
_COPYRIGHT = f"© {datetime.now(timezone.utc).year} {API_TITLE}. Academic / FYP demonstration."

_TEMPLATE_DISCLAIMER = (
    "This report was produced by a deterministic template from AI segmentation metrics. "
    "It is NOT a clinical diagnostic device. All findings require radiologist confirmation."
)

_BRACKET_SECTION = re.compile(
    r"\[\s*(FINDINGS|IMPRESSION|LONGITUDINAL ANALYSIS[^]]*|DISCLAIMER)\s*\]",
    re.IGNORECASE,
)


class PDFReportError(Exception):
    """PDF generation failed."""


@dataclass
class PDFReportContent:
    """Structured content rendered into the PDF layout."""

    report_type: ReportType
    patient_id: str
    generated_at: datetime
    patient_rows: list[tuple[str, str]]
    scan_rows: list[tuple[str, str]]
    lesion_rows: list[tuple[str, str]]
    findings: str
    impression: str
    recommendations: str
    disclaimer: str
    model_label: str = ""
    extra_sections: list[tuple[str, str]] = field(default_factory=list)


def _escape(text: str) -> str:
    return (
        str(text or "")
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _paragraph_text(text: str) -> str:
    cleaned = re.sub(r"\s+", " ", str(text or "").strip())
    return _escape(cleaned)


def _parse_template_sections(template_text: str) -> dict[str, str]:
    """Extract bracketed sections from :func:`analysis.report.generate_report` output."""
    text = template_text or ""
    matches = list(_BRACKET_SECTION.finditer(text))
    if not matches:
        return {}

    sections: dict[str, str] = {}
    for i, match in enumerate(matches):
        name = match.group(1).upper()
        if name.startswith("LONGITUDINAL"):
            key = "LONGITUDINAL"
        else:
            key = name.split()[0] if name in ("FINDINGS", "IMPRESSION", "DISCLAIMER") else name
        start = match.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[start:end].strip()
        body = re.sub(r"^\s*[-]+\s*", "", body)
        body = re.sub(r"\n{3,}", "\n\n", body).strip()
        if body:
            sections[key] = body
    return sections


def _default_recommendations() -> str:
    return (
        "Clinical correlation and qualified radiologist interpretation are recommended "
        "before any clinical decision-making."
    )


def _side_distribution_text(dist: dict[str, Any]) -> str:
    if not dist:
        return "N/A"
    return ", ".join(f"{v} focus(es) {k}" for k, v in dist.items())


def _build_common_rows(metadata: dict[str, Any]) -> tuple[list[tuple[str, str]], list[tuple[str, str]], list[tuple[str, str]]]:
    shape = metadata.get("shape") or []
    spacing = metadata.get("spacing_mm") or []
    shape_txt = " × ".join(str(s) for s in shape) if shape else "N/A"
    spacing_txt = " × ".join(f"{s} mm" for s in spacing) if spacing else "N/A"

    patient_rows = [
        ("Patient / Case ID", str(metadata.get("patient_id", "anonymised"))),
        ("Report modality", str(metadata.get("modality", "DWI MRI"))),
    ]
    scan_rows = [
        ("Volume dimensions (H×W×D)", shape_txt),
        ("Voxel spacing", spacing_txt),
        ("Voxel volume", f"{metadata.get('voxel_volume_ml', 'N/A')} mL"),
        ("AI segmentation system", str(metadata.get("ai_system", "2D U-Net"))),
    ]
    lesion_rows = [
        ("Lesion foci (AI count)", str(metadata.get("n_lesions", "N/A"))),
        ("Total lesion volume", f"{metadata.get('total_volume_ml', 'N/A')} mL"),
        ("Largest focus volume", f"{metadata.get('largest_volume_ml', 'N/A')} mL"),
        ("Side distribution", _side_distribution_text(metadata.get("side_distribution") or {})),
    ]

    per_lesion = metadata.get("per_lesion_findings") or []
    for i, finding in enumerate(per_lesion[:5], 1):
        lesion_rows.append((
            f"Focus {i}",
            (
                f"{finding.get('volume_ml', 'N/A')} mL, "
                f"{finding.get('side', 'N/A')} hemisphere, "
                f"{finding.get('region', 'N/A')}"
            ),
        ))
    if len(per_lesion) > 5:
        lesion_rows.append(("Additional foci", f"{len(per_lesion) - 5} smaller focus(es) omitted."))

    return patient_rows, scan_rows, lesion_rows


async def build_template_pdf_content(cache_entry: dict[str, Any]) -> PDFReportContent:
    """Build structured PDF content for a template report."""
    metadata = build_metadata_from_prediction_cache(cache_entry)
    case = cache_entry["case"]
    template_text = generate_report(
        case,
        patient_id=metadata["patient_id"],
        model_dice=None,
    )
    sections = _parse_template_sections(template_text)
    patient_rows, scan_rows, lesion_rows = _build_common_rows(metadata)

    extra: list[tuple[str, str]] = []
    if "LONGITUDINAL" in sections:
        extra.append(("Longitudinal analysis", sections["LONGITUDINAL"]))

    disclaimer = sections.get("DISCLAIMER", _TEMPLATE_DISCLAIMER)

    return PDFReportContent(
        report_type="template",
        patient_id=metadata["patient_id"],
        generated_at=datetime.now(timezone.utc),
        patient_rows=patient_rows,
        scan_rows=scan_rows,
        lesion_rows=lesion_rows,
        findings=sections.get("FINDINGS", "No findings section available."),
        impression=sections.get("IMPRESSION", "No impression section available."),
        recommendations=_default_recommendations(),
        disclaimer=disclaimer,
        model_label="Deterministic template (analysis.report)",
        extra_sections=extra,
    )


async def build_ai_pdf_content(cache_entry: dict[str, Any]) -> PDFReportContent:
    """Build structured PDF content from LLM sections (not raw model dump)."""
    metadata = build_metadata_from_prediction_cache(cache_entry)
    llm = await generate_llm_report(metadata)
    patient_rows, scan_rows, lesion_rows = _build_common_rows(metadata)

    return PDFReportContent(
        report_type="ai",
        patient_id=metadata["patient_id"],
        generated_at=datetime.now(timezone.utc),
        patient_rows=patient_rows,
        scan_rows=scan_rows,
        lesion_rows=lesion_rows,
        findings=llm.get("findings", ""),
        impression=llm.get("impression", ""),
        recommendations=llm.get("recommendations", ""),
        disclaimer=llm.get("disclaimer", LLM_DISCLAIMER),
        model_label=str(llm.get("model", "gemma:2b")),
        extra_sections=[],
    )


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle",
            parent=base["Heading1"],
            fontSize=16,
            leading=20,
            textColor=_COLOR_WHITE,
            alignment=TA_CENTER,
            spaceAfter=2,
        ),
        "subtitle": ParagraphStyle(
            "ReportSubtitle",
            parent=base["Normal"],
            fontSize=9,
            leading=12,
            textColor=_COLOR_WHITE,
            alignment=TA_CENTER,
        ),
        "section": ParagraphStyle(
            "SectionHead",
            parent=base["Heading2"],
            fontSize=11,
            leading=14,
            textColor=_COLOR_HEADER,
            spaceBefore=8,
            spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["BodyText"],
            fontSize=9.5,
            leading=13,
            textColor=_COLOR_INK,
            alignment=TA_LEFT,
        ),
        "muted": ParagraphStyle(
            "Muted",
            parent=base["BodyText"],
            fontSize=8,
            leading=11,
            textColor=_COLOR_MUTED,
        ),
        "footer": ParagraphStyle(
            "Footer",
            parent=base["Normal"],
            fontSize=7.5,
            leading=10,
            textColor=_COLOR_MUTED,
            alignment=TA_CENTER,
        ),
    }


def _header_table(st: dict[str, ParagraphStyle], subtype: str) -> Table:
    title = Paragraph(_REPORT_TITLE, st["title"])
    sub = Paragraph(
        f"{API_TITLE} · {subtype} report · v{API_VERSION}",
        st["subtitle"],
    )
    data = [[title], [sub]]
    tbl = Table(data, colWidths=[17 * cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), _COLOR_HEADER),
        ("BOX", (0, 0), (-1, -1), 0, _COLOR_HEADER),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
    ]))
    return tbl


def _info_table(rows: list[tuple[str, str]], col_widths: tuple[float, float]) -> Table:
    data = [[Paragraph(f"<b>{_escape(k)}</b>", _styles()["body"]),
             Paragraph(_paragraph_text(v), _styles()["body"])] for k, v in rows]
    tbl = Table(data, colWidths=[w * cm for w in col_widths], hAlign="LEFT")
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _COLOR_SECTION_BG),
        ("BACKGROUND", (0, 1), (-1, -1), _COLOR_WHITE),
        ("BOX", (0, 0), (-1, -1), 0.5, _COLOR_BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, _COLOR_BORDER),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
    ]))
    return tbl


def _section_block(st: dict[str, ParagraphStyle], heading: str, body: str) -> list:
    flow: list = [Paragraph(heading, st["section"])]
    flow.append(
        Table(
            [[Paragraph(_paragraph_text(body), st["body"])]],
            colWidths=[17 * cm],
            style=TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), _COLOR_SECTION_BG),
                ("BOX", (0, 0), (-1, -1), 0.5, _COLOR_BORDER),
                ("TOPPADDING", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]),
        )
    )
    flow.append(Spacer(1, 4 * mm))
    return flow


def _draw_footer(canvas, doc, content: PDFReportContent) -> None:
    canvas.saveState()
    ts = content.generated_at.strftime("%Y-%m-%d %H:%M UTC")
    footer_y = 15 * mm
    canvas.setStrokeColor(_COLOR_BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(20 * mm, footer_y + 10, A4[0] - 20 * mm, footer_y + 10)
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_COLOR_MUTED)
    canvas.drawCentredString(A4[0] / 2, footer_y + 2, _FOOTER_LINE)
    canvas.drawCentredString(A4[0] / 2, footer_y - 8, f"Generated: {ts} · {_COPYRIGHT}")
    canvas.restoreState()


def render_pdf(content: PDFReportContent) -> bytes:
    """Render :class:`PDFReportContent` to PDF bytes (A4)."""
    buffer = BytesIO()
    subtype = "Template" if content.report_type == "template" else "AI radiology"
    st = _styles()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=16 * mm,
        bottomMargin=28 * mm,
        title=_REPORT_TITLE,
        author=API_TITLE,
    )

    story: list = []
    story.append(_header_table(st, subtype))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("Patient information", st["section"]))
    story.append(_info_table(content.patient_rows, (4.2, 12.8)))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Scan information", st["section"]))
    story.append(_info_table(content.scan_rows, (4.2, 12.8)))
    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Lesion analysis", st["section"]))
    story.append(_info_table(content.lesion_rows, (4.5, 12.5)))
    story.append(Spacer(1, 5 * mm))

    if content.model_label:
        story.append(Paragraph(
            f"<i>Report source: {_escape(content.model_label)}</i>",
            st["muted"],
        ))
        story.append(Spacer(1, 3 * mm))

    story.extend(_section_block(st, "Findings", content.findings))
    story.extend(_section_block(st, "Impression", content.impression))
    story.extend(_section_block(st, "Recommendations", content.recommendations))

    for heading, body in content.extra_sections:
        story.extend(_section_block(st, heading, body))

    story.append(Spacer(1, 4 * mm))
    story.append(Paragraph("Disclaimer", st["section"]))
    story.append(
        Table(
            [[Paragraph(_paragraph_text(content.disclaimer), st["muted"])]],
            colWidths=[17 * cm],
            style=TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFFBEB")),
                ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#FDE68A")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ]),
        )
    )

    def on_page(canvas, doc_obj):
        _draw_footer(canvas, doc_obj, content)

    try:
        doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    except Exception as exc:
        raise PDFReportError(f"PDF rendering failed: {exc}") from exc

    return buffer.getvalue()


async def generate_report_pdf(
    cache_entry: dict[str, Any],
    report_type: ReportType,
) -> bytes:
    """Build PDF bytes for ``template`` or ``ai`` report types."""
    if report_type == "template":
        content = await build_template_pdf_content(cache_entry)
    elif report_type == "ai":
        content = await build_ai_pdf_content(cache_entry)
    else:
        raise PDFReportError(f"Unsupported report_type: {report_type!r}")

    if not content.findings.strip():
        raise PDFReportError("Report findings section is empty.")
    return render_pdf(content)


def pdf_filename(case_id: str, report_type: ReportType) -> str:
    safe = re.sub(r"[^\w.\-]+", "_", case_id or "case")[:80]
    return f"{safe}_{report_type}_report.pdf"
